// Generate a vendored vocabulary's CUE from the bytes it quotes.
//
//   deno run --allow-read=. --allow-write=. plugins/pronto/scales/build.ts
//
// Offline and read-only against the network: the input is the archive already
// checked in under scales/<tree>/, and refresh.ts is the only thing that
// fetches. The output is scales/*.cue, one file per tree, checked in beside it.
//
// Nothing here is trusted. Regenerating and diffing would prove this pass is
// deterministic, which a hardcoded table also is; what proves it QUOTED is the
// join invariants.sql runs over the same bytes on every `just lint`, in every
// app. This file is therefore free to be as plain as it looks.

import { type Admitted, vendorDeclarationsOf, vendoredNames, vendoredTrees } from "../scales.ts";


const SCALES = new URL("./", import.meta.url);

function fail(msg: string): never {
  console.error(`pronto scales build: ${msg}`);
  Deno.exit(1);
}

/** A CUE string literal. The vendored values carry no quote and no backslash,
 * and a value that started to would be escaped here rather than emitted raw. */
const cue = (s: string) => JSON.stringify(s);

for (const { dir, source } of await vendoredTrees()) {
  if (source.url === undefined || source.integrity === undefined) {
    fail(`${dir}/source.json states no url or no integrity, so its bytes have no provenance`);
  }
  const admitted: Admitted = JSON.parse(
    await Deno.readTextFile(new URL(`./${dir}/admitted.json`, SCALES)),
  );
  const refused = admitted.refused.map((r) => new RegExp(r.pattern));
  // A prefix alone cannot account for a declaration: every refused family of
  // Open Props' sizes nests under `--size-`, so dropping one refusal would let
  // its names in through a prefix that does not account for them. `keys`
  // is the shape the bucket's ladder is spelled in, and a name under the prefix
  // that does not wear it is unaccounted-for rather than admitted.
  const keys = new Map(admitted.admit.map((a) => [a.bucket, new RegExp(a.keys)]));

  // Insertion order is the archive's own declaration order, which is the order
  // the rung block is emitted in — so a reader diffing the emitted CSS against
  // upstream reads the two in the same sequence.
  const steps = new Map<string, Map<string, string>>(
    admitted.admit.map((a) => [a.bucket, new Map()]),
  );
  for (const [file, name] of vendoredNames(source.files)) {
    const css = await Deno.readTextFile(new URL(`./${dir}/${name}`, SCALES));
    for (const d of vendorDeclarationsOf(source.name, css)) {
      // Refusal is asked first because it is the stated argument, and a name
      // with one settles there rather than in the shape check below.
      if (refused.some((re) => re.test(d.token))) continue;
      const under = admitted.admit.filter((a) => d.token.startsWith(a.prefix));
      const entry = under.find((a) => keys.get(a.bucket)!.test(d.token.slice(a.prefix.length)));
      if (entry === undefined) {
        fail(
          under.length === 0
            ? `${dir}/${file} declares ${d.token}, which admitted.json neither admits nor refuses`
            : `${dir}/${file} declares ${d.token}, which falls under the admitted prefix ` +
              `${under.map((a) => a.prefix).join(" and ")} and wears none of that bucket's key ` +
              `shapes (${under.map((a) => a.keys).join(", ")}), so nothing here accounts for it`,
        );
      }
      steps.get(entry.bucket)!.set(d.token.slice(entry.prefix.length), d.value);
    }
  }
  const empty = [...steps].filter(([, s]) => s.size === 0).map(([b]) => b);
  if (empty.length > 0) fail(`${dir} admits ${empty.join(", ")} and the archive declares nothing under it`);

  const lines = [
    `// generated by pronto from plugins/pronto/scales/${dir} — do not edit`,
    "",
    "package scales",
    "",
    `${source.name}: {`,
    "\tsource: {",
    // A tree under scales/ is an archive this repository quotes, by
    // construction: the url and integrity above are what makes it one.
    `\t\tkind:      "quoted"`,
    `\t\torigin:    ${cue(source.origin)}`,
    `\t\tversion:   ${cue(source.version)}`,
    `\t\turl:       ${cue(source.url)}`,
    `\t\tintegrity: ${cue(source.integrity)}`,
    "\t}",
    "\tbuckets: {",
  ];
  for (const a of admitted.admit) {
    lines.push(
      `\t\t${a.bucket}: {`,
      `\t\t\tprefix:    ${cue(a.prefix)}`,
      `\t\t\tdimension: ${cue(a.dimension)}`,
      `\t\t\tsource:    ${cue(source.name)}`,
      "\t\t\tsteps: {",
      ...[...steps.get(a.bucket)!].map(([k, v]) => `\t\t\t\t${cue(k)}: ${cue(v)}`),
      "\t\t\t}",
      "\t\t}",
    );
  }
  lines.push("\t}", "}", "");
  const out = new URL(`./${source.name}.cue`, SCALES);
  await Deno.writeTextFile(out, lines.join("\n"));
  console.error(`build: ${source.name}.cue <- ${dir} (${[...steps].map(([b, s]) => `${b} ${s.size}`).join(", ")})`);
}
