// generated by pronto from plugins/pronto/scales/primer-primitives-11.10.0 — do not edit

package scales

primer: {
	source: {
		kind:      "quoted"
		origin:    "@primer/primitives"
		version:   "11.10.0"
		url:       "https://registry.npmjs.org/@primer/primitives/-/primitives-11.10.0.tgz"
		integrity: "sha512-ihZxIst4Izry284StKFjpbYvX6R/IBFTLu+qiuAmR93PsKF2hdjoabhSYwKI8iCxOUx94jVP55bI3NoY7STjYQ=="
	}
	buckets: {
		textSize: {
			prefix:    "--base-text-size-"
			dimension: "text"
			source:    "primer"
			steps: {
				"2xl": "2.5rem"
				"lg": "1.25rem"
				"md": "1rem"
				"sm": "0.875rem"
				"xl": "2rem"
				"xs": "0.75rem"
			}
		}
		textLineHeight: {
			prefix:    "--base-text-lineHeight-"
			dimension: "leading"
			source:    "primer"
			steps: {
				"loose": "1.75"
				"normal": "1.5"
				"relaxed": "1.625"
				"snug": "1.375"
				"tight": "1.25"
			}
		}
	}
}
