[env]
[env._]
file = '.bayt/.env'

[settings]
github_attestations = false
locked = true
lockfile = true
slsa = false

[settings.aqua]
cosign = false
github_attestations = false
minisign = false
slsa = false

[settings.github]
github_attestations = false
slsa = false

[tools]
'github:FiloSottile/mkcert' = 'v1.4.4'
'github:bonisoft3/bayt' = '0.58.4'
'github:bonisoft3/mecha' = '0.6.3'
'github:bonisoft3/omnishell' = '0.7.1'
'github:bonisoft3/pronto' = '0.8.5'
'github:bonisoft3/sayt' = '0.42.2'
'github:bufbuild/buf' = '1.73.0'
'github:caddyserver/caddy' = '2.10.0'
'github:cue-lang/cue' = '0.16.1'
'github:denoland/deno' = 'v2.9.7'
'github:redpanda-data/connect' = '4.46.0'
'github:sbdchd/squawk' = '2.66.0'

[tools.'http:duckdb']
version = '1.5.5'

[tools.'http:duckdb'.platforms]
[tools.'http:duckdb'.platforms.linux-arm64]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-linux-arm64.zip'

[tools.'http:duckdb'.platforms.linux-arm64-musl]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-linux-arm64-musl.zip'

[tools.'http:duckdb'.platforms.linux-x64]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-linux-amd64.zip'

[tools.'http:duckdb'.platforms.linux-x64-musl]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-linux-amd64-musl.zip'

[tools.'http:duckdb'.platforms.macos-arm64]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-osx-arm64.zip'

[tools.'http:duckdb'.platforms.macos-x64]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-osx-amd64.zip'

[tools.'http:duckdb'.platforms.windows-arm64]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-windows-arm64.zip'

[tools.'http:duckdb'.platforms.windows-x64]
url = 'https://github.com/duckdb/duckdb/releases/download/v{{ version }}/duckdb_cli-windows-amd64.zip'
