// generated by pronto from the cel: constraints in program.cue — do not edit
//
// `checks` are the SQL CHECK bodies emit.cue renders into the table DDL;
// `seed` carries what each field-level cel says about the field's own
// value, which is what vets a stated row; `enums` lists the values a
// closed constraint admits, for the readers that cannot enumerate a CUE
// disjunction, and `bounds` states what an open one admits — a range, a
// length, a pattern — for the readers that have to propose a value.
// An invariant binds `this` to the ROW, and a predicate over
// several columns constrains no single field's value, so it derives a
// CHECK body and nothing for CUE.
package truco

import "strings"

code: state: entities: {
	Match: {
		seed: [...{
			id?: strings.MaxRunes(64)
			variant?: ("paulista" | "mineiro" | "gaucho" | "truc" | "douradinha" | "douradao" | "argentino" | "uruguayo" | "paraguayo")
			seats?: ("1v1" | "2v2" | "2v2v2")
			theme?: ("xadrez" | "formica" | "neon" | "madeira")
			us_score?: >=0 & <=30
			them_score?: >=0 & <=30
			others_score?: >=0 & <=30
			stake?: (1 | 2 | 3 | 4 | 6 | 8 | 9 | 10 | 12)
			hand_no?: >=1
			status?: ("playing" | "over")
			winner?: ("" | "us" | "them" | "others")
			opponent?: ("nezinho" | "cida" | "tiao" | "ze" | "xiru" | "osvaldo" | "tiao_queijo" | "tabare" | "jordi" | "online")
			opponent_name?: strings.MinRunes(1)
			partner_name?: strings.MinRunes(1)
			seed?: strings.MaxRunes(12)
			my_seat?: ("" | "you" | "eles1")
			current?: ("yes" | "no")
			locale?: ("" | "pt-BR" | "es-AR" | "es-UY" | "es-PY" | "ca-ES")
		}]
		enums: {
			variant: ["paulista","mineiro","gaucho","truc","douradinha","douradao","argentino","uruguayo","paraguayo"]
			seats: ["1v1","2v2","2v2v2"]
			theme: ["xadrez","formica","neon","madeira"]
			stake: ["1","2","3","4","6","8","9","10","12"]
			status: ["playing","over"]
			winner: ["","us","them","others"]
			opponent: ["nezinho","cida","tiao","ze","xiru","osvaldo","tiao_queijo","tabare","jordi","online"]
			my_seat: ["","you","eles1"]
			current: ["yes","no"]
			locale: ["","pt-BR","es-AR","es-UY","es-PY","ca-ES"]
		}
		bounds: {
			id: {sizeMax: 64}
			us_score: {intMin: 0, intMax: 30}
			them_score: {intMin: 0, intMax: 30}
			others_score: {intMin: 0, intMax: 30}
			hand_no: {intMin: 1}
			opponent_name: {sizeMin: 1}
			partner_name: {sizeMin: 1}
			seed: {sizeMax: 12}
		}
	}
	Round: {
		seed: [...{
			id?: strings.MaxRunes(64)
			match_id?: strings.MaxRunes(64)
			hand_no?: >=1
			vira?: strings.MaxRunes(4)
			manilha?: strings.MinRunes(1)
			phase?: ("dealt" | "v1" | "v2" | "v3" | "result")
			truco_state?: ("" | "none" | "truco_called" | "retruco_called" | "vale4_called" | "truco_accepted" | "retruco_accepted" | "vale4_accepted" | "truco_folded")
			envido_state?: ("" | "none" | "called" | "real_called" | "falta_called" | "accepted" | "folded" | "flor")
			trick_state?: ("" | "dealt" | "v1_in_progress" | "v1_us" | "v1_them" | "v1_tie" | "v2_tie" | "result")
			ran?: ("" | "us" | "them" | "others")
			v1?: ("" | "us" | "them" | "others" | "tie")
			v2?: ("" | "us" | "them" | "others" | "tie")
			v3?: ("" | "us" | "them" | "others" | "tie")
			stake?: (1 | 2 | 3 | 4 | 6 | 8 | 9 | 10 | 12)
			result?: ("" | "us" | "them" | "others" | "draw" | "settled")
			leader?: ("you" | "parca" | "eles1" | "eles2" | "eles3" | "eles4")
			asked?: ("" | "you" | "parca" | "eles1" | "eles2" | "eles3" | "eles4")
			raised?: ("" | "us" | "them" | "others")
			rung?: >=0 & <=12
			brink?: ("" | "us" | "them" | "both")
			envido?: ("" | "called" | "scored" | "ran" | "flor")
			envido_asked?: ("" | "you" | "parca" | "eles1" | "eles2" | "eles3" | "eles4")
			envido_rung?: >=0 & <=30
			envido_calls?: strings.MaxRunes(40)
			envido_us?: >=0 & <=33
			envido_them?: >=0 & <=33
			envido_result?: ("" | "us" | "them" | "others")
			said?: strings.MaxRunes(60)
			turn_seat?: ("" | "you" | "parca" | "eles1" | "eles2" | "eles3" | "eles4")
			current?: ("yes" | "no")
		}]
		enums: {
			phase: ["dealt","v1","v2","v3","result"]
			truco_state: ["","none","truco_called","retruco_called","vale4_called","truco_accepted","retruco_accepted","vale4_accepted","truco_folded"]
			envido_state: ["","none","called","real_called","falta_called","accepted","folded","flor"]
			trick_state: ["","dealt","v1_in_progress","v1_us","v1_them","v1_tie","v2_tie","result"]
			ran: ["","us","them","others"]
			v1: ["","us","them","others","tie"]
			v2: ["","us","them","others","tie"]
			v3: ["","us","them","others","tie"]
			stake: ["1","2","3","4","6","8","9","10","12"]
			result: ["","us","them","others","draw","settled"]
			leader: ["you","parca","eles1","eles2","eles3","eles4"]
			asked: ["","you","parca","eles1","eles2","eles3","eles4"]
			raised: ["","us","them","others"]
			brink: ["","us","them","both"]
			envido: ["","called","scored","ran","flor"]
			envido_asked: ["","you","parca","eles1","eles2","eles3","eles4"]
			envido_result: ["","us","them","others"]
			turn_seat: ["","you","parca","eles1","eles2","eles3","eles4"]
			current: ["yes","no"]
		}
		bounds: {
			id: {sizeMax: 64}
			match_id: {sizeMax: 64}
			hand_no: {intMin: 1}
			vira: {sizeMax: 4}
			manilha: {sizeMin: 1}
			rung: {intMin: 0, intMax: 12}
			envido_rung: {intMin: 0, intMax: 30}
			envido_calls: {sizeMax: 40}
			envido_us: {intMin: 0, intMax: 33}
			envido_them: {intMin: 0, intMax: 33}
			said: {sizeMax: 60}
		}
	}
	Play: {
		seed: [...{
			id?: strings.MaxRunes(64)
			round_id?: strings.MaxRunes(64)
			vaza?: >=1 & <=3
			seat?: ("you" | "parca" | "eles1" | "eles2" | "eles3" | "eles4")
			kind?: ("card" | "truco" | "accept" | "run" | "envido" | "envido_real" | "envido_falta" | "envido_take" | "envido_run" | "envido_count" | "envido_good" | "flor" | "brink_play")
			count?: strings.MaxRunes(2)
			card?: strings.MaxRunes(4)
			power?: >=0 & <=100
			said?: strings.MaxRunes(24)
			from_slot?: >=0 & <=2
			rank?: strings.MaxRunes(2)
			suit?: ("" | "♠" | "♥" | "♦" | "♣")
			face?: strings.MaxRunes(2)
			manilha?: ("" | "yes" | "no")
			lie?: >=-7 & <=7
			win?: ("" | "yes")
			seq?: strings.MinRunes(2) & strings.MaxRunes(2)
		}]
		enums: {
			seat: ["you","parca","eles1","eles2","eles3","eles4"]
			kind: ["card","truco","accept","run","envido","envido_real","envido_falta","envido_take","envido_run","envido_count","envido_good","flor","brink_play"]
			suit: ["","♠","♥","♦","♣"]
			manilha: ["","yes","no"]
			win: ["","yes"]
		}
		bounds: {
			id: {sizeMax: 64}
			round_id: {sizeMax: 64}
			vaza: {intMin: 1, intMax: 3}
			count: {sizeMax: 2}
			card: {sizeMax: 4}
			power: {intMin: 0, intMax: 100}
			said: {sizeMax: 24}
			from_slot: {intMin: 0, intMax: 2}
			rank: {sizeMax: 2}
			face: {sizeMax: 2}
			lie: {intMin: -7, intMax: 7}
			seq: {sizeMin: 2, sizeMax: 2}
		}
	}
	Held: {
		seed: [...{
			id?: strings.MaxRunes(64)
			round_id?: strings.MaxRunes(64)
			seat?: ("you" | "parca" | "eles1" | "eles2" | "eles3" | "eles4")
			card?: (strings.MaxRunes(4) | "back")
			rank?: strings.MaxRunes(2)
			suit?: ("" | "♠" | "♥" | "♦" | "♣")
			face?: strings.MaxRunes(2)
			power?: >=0 & <=100
			manilha?: ("" | "yes" | "no")
			slot?: >=0 & <=2
			blocked?: ("" | "disabled")
			display_seat?: ("" | "you" | "eles1" | "parca" | "eles2")
			current?: ("yes" | "no")
		}]
		enums: {
			seat: ["you","parca","eles1","eles2","eles3","eles4"]
			suit: ["","♠","♥","♦","♣"]
			manilha: ["","yes","no"]
			blocked: ["","disabled"]
			display_seat: ["","you","eles1","parca","eles2"]
			current: ["yes","no"]
		}
		bounds: {
			id: {sizeMax: 64}
			round_id: {sizeMax: 64}
			rank: {sizeMax: 2}
			face: {sizeMax: 2}
			power: {intMin: 0, intMax: 100}
			slot: {intMin: 0, intMax: 2}
		}
	}
	Lobby: {
		checks: {
			id: "char_length(id) <= 64"
			handle: "char_length(handle) > 0 AND char_length(handle) <= 40"
			room_seed: "char_length(room_seed) <= 64"
			status: "status IN ('waiting', 'playing')"
		}
		seed: [...{
			id?: strings.MaxRunes(64)
			handle?: strings.MinRunes(1) & strings.MaxRunes(40)
			room_seed?: strings.MaxRunes(64)
			status?: ("waiting" | "playing")
		}]
		enums: {
			status: ["waiting","playing"]
		}
		bounds: {
			id: {sizeMax: 64}
			handle: {sizeMin: 1, sizeMax: 40}
			room_seed: {sizeMax: 64}
		}
	}
	Challenge: {
		checks: {
			id: "char_length(id) <= 64"
			challenger_id: "char_length(challenger_id) <= 64"
			challenger_name: "char_length(challenger_name) > 0 AND char_length(challenger_name) <= 40"
			target_id: "char_length(target_id) <= 64"
			seed: "char_length(seed) <= 64"
			status: "status IN ('pending', 'accepted', 'declined', 'expired')"
		}
		seed: [...{
			id?: strings.MaxRunes(64)
			challenger_id?: strings.MaxRunes(64)
			challenger_name?: strings.MinRunes(1) & strings.MaxRunes(40)
			target_id?: strings.MaxRunes(64)
			seed?: strings.MaxRunes(64)
			status?: ("pending" | "accepted" | "declined" | "expired")
		}]
		enums: {
			status: ["pending","accepted","declined","expired"]
		}
		bounds: {
			id: {sizeMax: 64}
			challenger_id: {sizeMax: 64}
			challenger_name: {sizeMin: 1, sizeMax: 40}
			target_id: {sizeMax: 64}
			seed: {sizeMax: 64}
		}
	}
	RoomAction: {
		checks: {
			id: "char_length(id) <= 64"
			room_seed: "char_length(room_seed) <= 64"
			player_id: "char_length(player_id) <= 64"
			action: "action IN ('play_card', 'truco', 'accept', 'run', 'touch_card', 'resign')"
			card: "char_length(card) <= 4"
			slot: "slot >= 0 AND slot <= 12"
		}
		seed: [...{
			id?: strings.MaxRunes(64)
			room_seed?: strings.MaxRunes(64)
			player_id?: strings.MaxRunes(64)
			action?: ("play_card" | "truco" | "accept" | "run" | "touch_card" | "resign")
			card?: strings.MaxRunes(4)
			slot?: >=0 & <=12
		}]
		enums: {
			action: ["play_card","truco","accept","run","touch_card","resign"]
		}
		bounds: {
			id: {sizeMax: 64}
			room_seed: {sizeMax: 64}
			player_id: {sizeMax: 64}
			card: {sizeMax: 4}
			slot: {intMin: 0, intMax: 12}
		}
	}
}
