// generated by pronto from the ir and the screen markup — do not edit
package truco

code: surface: screens: {
	arena: {
		reads: [
			{table: "match", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
			{table: "match", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
			{table: "match", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
			{table: "match", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
			{table: "match", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
			{table: "match", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: ["created_at"]},
			{table: "match", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "live", nested: true, lists: [10], route: "view", clauses: [{"col":"round_id","op":"eq"}], embeds: [], orders: ["seq"]},
			{table: "match", kind: "reads", nested: true, lists: [10], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: true, lists: [10], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: true, lists: [10], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: true, lists: [10], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: true, lists: [10], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"},{"col":"display_seat","op":"eq"}], embeds: [], orders: ["slot"]},
			{table: "held", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"},{"col":"display_seat","op":"eq"}], embeds: [], orders: ["slot"]},
			{table: "held", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"},{"col":"display_seat","op":"eq"}], embeds: [], orders: ["slot"]},
			{table: "held", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"},{"col":"display_seat","op":"eq"}], embeds: [], orders: ["slot"]},
			{table: "held", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"},{"col":"display_seat","op":"eq"}], embeds: [], orders: ["slot"]},
			{table: "round", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: ["created_at"]},
			{table: "play", kind: "live", nested: true, lists: [27], route: "view", clauses: [{"col":"round_id","op":"eq"},{"col":"vaza","op":"eq"},{"col":"kind","op":"eq"}], embeds: [], orders: ["seq"]},
			{table: "play", kind: "live", nested: true, lists: [27], route: "view", clauses: [{"col":"round_id","op":"eq"},{"col":"vaza","op":"eq"},{"col":"kind","op":"eq"}], embeds: [], orders: ["seq"]},
			{table: "play", kind: "live", nested: true, lists: [27], route: "view", clauses: [{"col":"round_id","op":"eq"},{"col":"vaza","op":"eq"},{"col":"kind","op":"eq"}], embeds: [], orders: ["seq"]},
			{table: "round", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
			{table: "match", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"},{"col":"display_seat","op":"eq"}], embeds: [], orders: ["slot"]},
			{table: "match", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
			{table: "match", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "match", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "match", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: true, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "lobby", kind: "live", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: ["handle"]},
			{table: "challenge", kind: "live", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: ["created_at"]},
			{table: "room_action", kind: "live", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: ["created_at"]},
			{table: "match", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "round", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "play", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "held", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
			{table: "room_action", kind: "reads", nested: false, lists: [], route: "whole", clauses: [], embeds: [], orders: []},
		]
		writes: [
			{table: "match", op: "reduce"},
			{table: "round", op: "reduce"},
			{table: "play", op: "reduce"},
			{table: "held", op: "reduce"},
			{table: "room_action", op: "reduce"},
		]
		files: {handlers: ["shell/handlers/seats2.js", "shell/handlers/sitting.js", "shell/handlers/spun.js", "shell/handlers/stake0.js", "shell/handlers/table.js", "shell/handlers/variant2.js", "shell/handlers/variant3.js"], adapters: []}
	}
	regras: {
		reads: [
			{table: "match", kind: "live", nested: false, lists: [], route: "view", clauses: [{"col":"current","op":"eq"}], embeds: [], orders: []},
		]
		writes: []
		files: {handlers: [], adapters: []}
	}
}

_irNotes: {
	"decision-01": "01 — nothing leaves the device, and the sitting outlives the tab. The brief asks for a game that owes the network nothing, and durability is the axis that buys it. The hand is tab: a round, its plays and the cards you hold are the sitting itself and have no meaning after it. The match is device, because a score you were in the middle of is worth finding again tomorrow, and that is one word of program rather than a different kind of app. Neither rung emits a table, trigger, publication, policy or migration; neither syncs. The cost is stated rather than hidden: there is still no cross-device anything, and a browser that forgets its storage forgets the score. The right cost for a bar game and the wrong one for a ledger"
	"decision-02": "02 — the dealer is the one escape, and it is app-owned code. Pronto's declarative surface has no way to express a shuffle, a card's power under a variant, or an opponent's choice. The terminal's Jessie handler contract does not fit either: it is a pure reduce whose only event source is a drag. So the arena carries an app-owned module. This is a genuine hole in the guarantees and it is drawn as its own box (dealer) rather than spread through the markup"
	"decision-03": "03 — the dealer writes only through forms. Every mutation it decides goes through the arena's own emitted forms, filled and submitted. Two things follow: the store keeps exactly one write path, so a row the app holds is a row a region can render; and the machine's writes are auditable in the same place as the player's. The cards in flight are the deliberate exception — a hand of cards is not a record, and persisting one would make the store's contents depend on when you looked"
	"decision-04": "04 — no pipelines. A pipeline consumes CDC events off the cluster's WAL; a tab entity has no table to publish. Every derivation a pipeline would carry — the running score, the vaza tally — is decided by the dealer at the moment of play and written as an ordinary field. The idempotence argument that a pipeline would owe is replaced by a simpler one: each of these writes is a single form submission against a row the dealer already holds"
	"decision-05": "05 — the phase spine is a field, not markup state. Round.phase is one text column and the tracker is a region over it. The alternative — the screen keeping its own idea of the phase — puts the spine and the hand out of step exactly when a vaza resolves, which is the moment the tracker exists for"
	"decision-06": "06 — switching variant restarts the match. Paulista and Mineiro do not merely differ in manilhas; the ladder starts at a different rung, so a score carried across the switch would be a score no rulebook produced. Restarting is honest and the dropdown says so"
	"decision-07": "07 — a table turns a card up or fixes its manilhas, never both. Paulista and gaúcho turn a vira and read the rank above it. Mineiro and the Río de la Plata tables name four cards in the rules and turn nothing, so the round carries no vira and the strip that names one is not drawn — a slot showing a card nobody laid is what reads as a bug, and it is the reading the fixed-manilha player is most likely to make"
	"decision-08": "08 — the log is append-only. Play is never updated or deleted, not even between hands. It makes the hand auditable during play, gives the QA seat a surface it can drive assertions against, and removes a class of bug the store would otherwise hold: a rewritten log cannot be told from a misplayed hand"
	"decision-09": "09 — a finished match is closed, not deleted. status moves to over and the arena's singleton read stops matching it, so the closing scoreline stays on screen until a new match is asked for. Deleting would take the result off the table at the moment it is being read"
	"decision-10": "10 — every picker is the app's own dropdown. The brief demands no OS popup, and the reason is the design's: a native select menu is drawn by the operating system, and an OS menu on a felt table breaks the object the whole screen is building. The panel is the graduated omnishell--picker: selection is a machine over the match row, and hidden-by-default, top layer, light dismiss, Escape and focus return are the platform popover's own — what the app still owes is only which option is checked, kept by the screen's observer"
	"decision-11": "11 — the four themes are app-private tokens. Felt Emerald, Midnight Obsidian, Cyber Neon and Crimson Dragon retint the mat, frame and card backs through [data-theme] scopes over the app's own token names in a shared stylesheet. They never redeclare a platform token, so the design system keeps its single declaration and the light/dark twin stays orthogonal: a theme is a material, an appearance is the room"
	"decision-12": "12 — keep policy: arena 0, regras 1. The table is dealt on arrival, so holding a stale instance would show a hand that no longer exists; the rules screen is consulted mid-hand and holding it keeps the scroll position where the reader left it"
	"decision-13": "13 — no auth block. The terminal offers passkey and guest; this app declares neither, because nothing here is per-person and a sign-in gate on a bar game is a toll. The profile bar shows the seat — an avatar, the title the score earns, and the word convidado — and it is honest about being local"
	"decision-14": "14 — escape hatches: none. No container, no WASM, no external endpoint, no vendored unit. The one hole in the declarative guarantees is the dealer (decision-02), which is app code at the terminal tier, not a cluster service; the emitted bayt.cue redeclares the runtime trio unchanged"
	"decision-15": "15 — one looping animation, and it is the stake. Cards lift, the mat settles, ticks stamp, the score counts — all transitions on the motion tokens, so reduced motion collapses them. The stake badge's pulse is the single loop in the app and it runs only while the hand is raised, which is the one state a player must not miss"
	"decision-16": "16 — the house plays correctly, not deviously. Lowest winning card, else lowest card; it accepts a raise when its hand is strong and runs when it is not. Bluffing and card counting are declined at this stage: an opponent that lies is only fun once the player trusts the table, and trust is built by an opponent whose moves can be checked against the rules screen"
	"decision-17": "17 — no sound. The brief does not ask for it, the terminal publishes no audio capability, and a card game that makes noise in a browser tab is a card game people mute. The settle and the pulse carry the feedback instead"
	"decision-18": "18 — the board is a fixed viewport object, not a page. The arena occupies exactly the viewport minus the terminal's nav strip and never scrolls: a table you have to scroll is a web page, and the felt stops being an object the moment part of it is somewhere else. Every size inside is viewport-relative — the card is a fraction of the shorter side, the score figures and the spine scale with it — so a phone in portrait and a desktop across the room get the same board rather than two layouts. On a desktop it stops growing at a table's worth of space and sits in the middle of the room; on a phone it fills the screen"
	"decision-19": "19 — every screen rule is nested under its own screen. The terminal injects a screen's stylesheet into the document head and it outlives the screen that brought it, so a bare .mat rule reaches every screen that follows. This app has two screens sharing a material vocabulary, and the arena's grid tore the rules screen apart until both were nested under [data-screen]. The shared layer (shell/shared/table.css) stays unscoped on purpose: it is the vocabulary both screens speak"
	"decision-20": "20 — nobody bids against themselves. The side that called truco cannot call the next rung: once its raise is accepted the right to climb belongs to the other side, and the call button says so rather than going quietly inert. Answering a raise with a higher one is still one gesture, and it is recorded as two — the rung on the table is accepted, then the next is called — because that is what the log has to be able to replay"
	"decision-21": "21 — the table keeps its cards. Played cards are not collected between tricks; each closed trick stays on the felt, smaller and dimmed, with the card that took it still lit. A player who looked away can read the whole hand off the table, which is what a real table gives free and a screen has to be told to do. It also retires the sweep animation an earlier pass had: the cards going somewhere was a poor substitute for the cards still being there"
	"decision-22": "22 — the table speaks the variant's words. In Paulista a trick is a vaza and the race to twelve is a partida; in Minas the trick is a rodada and the race to twelve is a jogo, and both call the three-trick deal a mão. Queda is neither, and it is not another word for jogo: a jogo is the race to twelve tentos, a queda is the best of three jogos — the side that takes two — and it is the tier above the ladder, never a rung on it. This app plays a single jogo and keeps no queda tally, so it does not use the word at all. The first pass had all three wrong (trick as queda, match as jogo) on nothing better than a guess; the owner sent it back and the sources settled it. The vocabulary follows the rules in force everywhere — the table's line, the rules screen, the log — because a Mineiro player reading \"vaza\" is being told the app learned the game somewhere else. Both words ship as real text with the inactive one removed, never as generated content: a sentence assembled out of ::before is a sentence nobody can select, search, or hear"
	"decision-23": "23 — the mão passes, and the pé is a position the table shows. The player who leads a hand is the mão; the last to play is the pé, and the pé has the final word on every trick of it — which is why a player wants to know which one they are before they choose a card. The lead had been fixed on the player, which is not the game: it passes one seat every hand, and the seat bar wears the position"
	"decision-24": "24 — the bot was bought, measured, and declined. Rather than reason out a better opponent, the obvious move was to take one off the shelf: npm:mcts (MIT, a hundred lines, four methods) wired to these rules, with the hidden hand handled by determinization — sample the unseen cards, search that perfect-information game, vote. Measured over the same 1,200 deals it lost: 44.5% at four samples, 46.3% at sixteen, against the shipped heuristic's 50%, at 22ms a hand. The reason is structural rather than a bad adapter: a truco hand is three cards, so the tree is too small for search to find anything the heuristic misses, while random playouts are noisier than a rule that is nearly right. The library stays out. Where a bot could still pay is the betting, and that is where the sweep below put its numbers"
	"decision-25": "25 — eles have names. \"A casa\" is a poker word: the house, the bank, the institution that cannot be beaten. Truco has no house — it has the other pair, who are as beatable as you are, which is why a truco scoreboard says NÓS and ELES and never \"the house\". The seats are renamed to match, and the opponents become a small cast (Seu Nezinho, Dona Cida, Tião Pandeiro, Zé da Bicicleta, and Bigode as the parça), each a set of betting thresholds around the swept centre with a face and a line. Each also has a tell that lands a beat before their call — the Punch-Out!! bargain, where the opponent tells you what is coming and it is your job to be looking. It moves the game's tension from chance to attention"
	"decision-26": "26 — the house's numbers are swept, not reasoned. The first pass rated a hand by mean card power, which one manilha dominates: (100, 1, 2) averages 34 and (10, 9, 8) averages 9, though the second hand wins far more often. Capping each card at \"a card that reliably takes a trick\" first ranks hands half again as well (r .54 against .39 over 30k deals). The thresholds on top of it were then swept rather than argued: pot odds say a hand worth 1 raised to 3 is worth taking above 33%, which is most hands — and playing it that way lost 0.058 tentos a hand, because the odds of a hand as dealt are not its odds against somebody who just raised. The swept pair (call at 8.0, take at 7.0) wins 0.016 instead, and the personas are that pair moved around"
	"decision-27": "27 — the app checks its own fit. The platform's visual battery measures tap targets, overlap and viewport bounds, and reported zero findings while the call button sat under the board and small type measured 1.0 against its background. Neither is a gap in its judgment: a control clipped by an overflow: hidden ancestor is inside the viewport, and the battery does not compute contrast at all. So the app declares tests/fit.ts at integrate — every control's box against the board's box, every piece of small type against what is actually behind it, across five window shapes and all four tables. It caught both regressions the same afternoon they were written, which is the argument for app-declared checks in general: the platform's battery is a floor, and an app with an unusual surface owes itself the rest"
	"decision-28": "28 — the card face is two corners and one mark, chosen at 53px. The face shipped as a corner rank with one large pip in the middle. Three faces were drawn and rendered at the three sizes the table actually uses — 53px (a short window), 69px (a phone), 117px (a desk): the shipped one, a real baralho with counted pips and lettered courts, and rank-and-suit in both corners with a single central mark. The counted pips lose at 53px, where six and seven are the same smudge, so they lose outright: one face has to serve every size. The two-corner face wins on a functional argument rather than a decorative one — a fanned hand shows nothing but the top-left corner, so rank and suit belong there together, and the shipped face put the suit in the middle where an overlapped card hides it. Court cards keep their letter: a drawn figure at 53px is a smudge too"
	"decision-29": "29 — the hands and the felt are rows, so the terminal can keep its nodes. The felt is three regions over the play log, one per rodada, so a card already down is never replaced under the eye and a rodada that closes keeps its own node — which is what lets the shrink it takes on be a transition of something already on the table rather than an element born small. A played card carries the angle it lies at and what it renders with for the same reason a held one does: a template binds fields and cannot compute. Every hand at the table is rows — one per card, carrying the seat that holds it. Yours is the one with a template: the cards persist across every unrelated redraw, and they are the only thing on the felt a player touches. The seats across from you are still drawn as backs, but from their rows rather than from a count, because an engine evaluated in a compartment has no memory between calls and a hand it cannot read is a hand it cannot play. So they are a tab-path entity read by a region that names a seat, and the terminal's keyed reconciliation owns their identity: item nodes persist across refreshes, patched rather than replaced. Drawn imperatively they were rebuilt on every store change, which replayed the deal animation on every move and left no node alive long enough to animate a card out of the hand. The row carries its rendered parts (rank, suit, face) because a template binds fields and cannot compute one from another"
	"decision-30": "30 — the fold's clock is the terminal's, and it asks. A handler is evaluated in a compartment with nothing endowed and therefore has no clock, so a table that pauses between plays cannot time itself: it returns the pause it wants along with its writes, and the terminal calls it again when the pause is over. An earlier pass gave it a clock the other way round, as a CSS animation on the felt whose end arrived as an event; that worked, but it had to be exempted from the reduced-motion sweep — which collapses every animation to a millisecond — or the game ran at infinite speed for exactly the people who asked for calm. A pause the reduce asks for has no such problem, and the felt keeps no clock at all. Which animation ended is still carried on the event where one is: every animation inside a region bubbles to it, the terminal's own item arrivals included"
	"decision-31": "31 — whose turn it is is a fold over the log. A card may be tapped exactly when it is your turn to lay one, and that follows from the cards already laid: the rodada in play is the first without a verdict, its lead is whoever took the one before, and the seats fill it in order. So it is folded out of the log and written onto the hand, rather than stated by the dealer out of a model only the dealer can see — which is what made the screen right for only as long as that model was. Two facts no card states are carried instead: the round records who led its first rodada, and the match records how many seats are playing"
	"decision-32": "32 — the hand plays itself out of its own log. Everything between the deal and the score is one Jessie fold: whose turn it is, what eles lay, when they raise and how they answer, which side took each rodada, and what the hand was worth. None of it is a decision the log does not already imply, which is why it can run in a compartment with nothing endowed — rows in, updates out, no DOM and no clock. The deal is there too. A compartment has no randomness, but a sitting needs only one draw: the match keeps it, and every shuffle in the match follows from that and the hand's number. Which also buys something the dealer's own generator never could — a match replays out of its own rows, so a hand that broke is a repro rather than a story. Even the draw that opens a sitting is asked for rather than taken: the fold says it wants one and is called again with it, the way it says it wants to wait. Nothing about the table reaches the store through a form any more, and the dealer keeps the screen. What you do reaches the table as a row and nothing else, and every consequence of it is the fold's, so there is one writer for each fact rather than a model in the dealer running alongside the rows. Every value a row carries is written as text, because the dealer's writes arrive through form inputs and a region's filter compares a column against the text standing in the markup: a number where the rest of the table keeps a string is a row the felt cannot see"
	"decision-33": "33 — one rail that shows the live call, with the suspended one drawn above it. With flor, real envido and falta envido a first rodada can hold five callable things at once, on a phone, over the hand. Three layouts were drawn. Two rails give the second wager its own fixed strip in gold above the hand, which never surprises anyone and costs height in the one rodada where the hand matters most. Table talk puts each call beside whoever said it and keeps one small cluster of buttons, which is the truest to a bar table and the least conventional. One rail carries whichever call is live and draws the outstanding truco above it as a dashed strip that says what it is worth and that it is still waiting. The one rail wins on the thing the round was built around: a truco answered with envido leaves that truco standing, and this is the only one of the three where the player can see it standing rather than having to remember it. The mechanism and the picture agree. Its cost is real and accepted — the rail means different things at different moments, so the rail is labelled with the wager it is currently asking about, and the two wagers are told apart by colour rather than by position: truco keeps the ink of --primary, the envido family takes --accent, and flor takes --attention. Colour carries the distinction the fixed positions used to"
	"decision-34": "34 — a tie is laid side by side, and so is the rodada that breaks it. Cards played to a rodada land across each other, each at its own angle, because that is how they fall on a table. A tie is the exception players make by hand: the rodada that settles it is played by showing the highest card, and cards being compared are set down next to each other, square, rather than on top. Three treatments were shot on the real table: only the deciding rodada opened; the deciding rodada and the tie it settles both opened; and the deciding rodada stood upright with a lit edge, as a card held up to be seen. The second was chosen. Opening the tie as well means a finished hand reads off the felt as what happened — a tie, then the rodada that broke it — without the phase tracker. Only the look changes: the verdict, the order of play and the rules are the same"
	"decision-35": "35 — opponent identity anchors to the north stage and scoreboard. Playing online against another person previously obscured who was sitting across the table: the opponent avatar had no nameplate or handle tag, the scoreboard bound an unmapped key that evaluated to empty, and the top bar displayed only the local player's handle, creating confusion about who was who. The opponent seat now owns its presence at the north stage with an explicit handle, online pill badge, role label, and monogram avatar disc. The scoreboard prints the opponent's actual name rather than a generic fallback. The local player's seat profile remains cleanly anchored in the seatbar with explicit attribution, keeping the felt actions completely unobstructed across all device viewports"
}

_deriving: *false | bool @tag(derive,type=bool)

if !_deriving {
	code: meta: decisions: [Id=string]: note: _irNotes[Id]
}

_irAccepts: {
	"test-card-order": ["accept-card-order"]
	"test-custom-dropdown": ["accept-custom-dropdown"]
	"test-dark-twin": ["accept-dark-twin"]
	"test-deal-shuffle": ["accept-fresh-shuffle","accept-instant-table"]
	"test-envido-count": ["accept-envido-count"]
	"test-envido-ladder": ["accept-envido-ladder"]
	"test-envido-pays-now": ["accept-envido-pays-now"]
	"test-flor-cancels": ["accept-flor-cancels"]
	"test-fog-of-war": ["accept-fog-of-war"]
	"test-gaucho-river": ["accept-gaucho-river","accept-gaucho-voltas"]
	"test-hand-winner": ["accept-hand-winner"]
	"test-house-answers": ["accept-house-answers"]
	"test-manilha-order": ["accept-manilha-order"]
	"test-mao-and-pe": ["accept-mao-and-pe"]
	"test-mao-de-dez": ["accept-mao-de-dez"]
	"test-match-to-twelve": ["accept-match-to-twelve","accept-match-over"]
	"test-mineiro-manilha": ["accept-mineiro-manilha"]
	"test-multiplayer-room": ["accept-multiplayer-room"]
	"test-next-hand": ["accept-next-hand"]
	"test-no-manilha": ["accept-no-manilha"]
	"test-no-self-raise": ["accept-no-self-raise"]
	"test-nos-eles": ["accept-nos-eles"]
	"test-offline": ["accept-offline"]
	"test-paulista-manilha": ["accept-paulista-manilha"]
	"test-persona-tell": ["accept-persona-tell"]
	"test-phase-spine": ["accept-phase-tracker"]
	"test-play-log": ["accept-play-log"]
	"test-profile-bar": ["accept-profile-bar"]
	"test-rules-screen": ["accept-rules-screen"]
	"test-run-scores": ["accept-run-scores"]
	"test-same-table": ["accept-same-table"]
	"test-seat-modes": ["accept-seat-modes","accept-partner-plays"]
	"test-shared-suit-order": ["accept-shared-suit-order"]
	"test-slot-tracking": ["accept-slot-tracking"]
	"test-stake-badge": ["accept-stake-badge"]
	"test-table-memory": ["accept-table-memory"]
	"test-theme-persists": ["accept-theme-switch"]
	"test-touch-and-motion": ["accept-touch-and-motion"]
	"test-truco-ladder": ["accept-truco-call","accept-raise-ladder"]
	"test-turn-clock": ["accept-turn-clock"]
	"test-variant-switch": ["accept-variant-switch"]
	"test-variant-words": ["accept-variant-words"]
	"test-vaza-tie": ["accept-vaza-tie"]
	"test-vaza-winner": ["accept-vaza-winner","accept-play-card"]
}

if !_deriving {
	code: meta: tests: [Id=string]: accepts: _irAccepts[Id]
}
