// omnishell's command line: the entry point every consumer of the terminal
// reaches its checkers through.
//
//   omnishell check markup|handlers|machines|battery <appDir> | --self-test
//   omnishell read markup <appDir> | --self-test
//   omnishell mode <appDir> [--local]
//
// What a check needs from deno — a lockfile policy, a type-check policy, a
// module resolution, a config, a permission grant, the path to a program —
// is the tool's business and not its caller's, so all of it lives behind this
// entry: the launcher beside this file states the deno half, and each leaf
// below states what it runs on. A caller writes a command.
//
// Every leaf's output is its checker's own — the findings JSON on stdout, the
// count on stderr, the exit code the severity band decides. Nothing here
// prints, so a caller parsing stdout parses what the checker said.

import { fileURLToPath, pathToFileURL } from "node:url";

const root = new URL("../", import.meta.url);

// A directory of the tool's own tree, spelled the way the filesystem does —
// which is what a permission descriptor is matched against, and what a URL
// pathname, percent-encoded and drive-prefixed, is not.
function toolDir(name: string): string {
  return fileURLToPath(new URL(name, root));
}

const usage = [
  "usage: omnishell check markup|handlers|machines|battery|parity|i18n <appDir> | --self-test",
  "       omnishell read markup <appDir> | --self-test",
  "       omnishell mode <appDir> [--local]",
].join("\n");

function refuse(message: string): never {
  console.error(message);
  console.error(usage);
  Deno.exit(1);
}

async function narrow(env: boolean): Promise<void> {
  await Deno.permissions.revoke({ name: "write" });
  if (!env) await Deno.permissions.revoke({ name: "env" });
}

// A URL's own spelling of a directory, as the arithmetic below needs it:
// decoded, and without the trailing slash that would leave an empty segment.
// Separators stay URL separators, so an app names this runtime the same way on
// every platform and the stanza a checkout generates is one file.
function dirPath(url: URL): string {
  return decodeURIComponent(url.pathname).replace(/\/+$/, "");
}

// A directory named from another one, which is how an app names this runtime:
// the commands run in the app's directory, so the path is stated from there.
function pathFrom(base: string, target: string): string {
  const here = base.split("/");
  const there = target.split("/");
  let shared = 0;
  while (shared < here.length && shared < there.length && here[shared] === there[shared]) shared++;
  return [...here.slice(shared).map(() => ".."), ...there.slice(shared)].join("/");
}

// The stanza that tells an app's program which terminal its commands name: this
// tree, stated as a path from the app, or the empty string for the installed
// `omnishell`, whose files are then named from its own root (where mise put
// it, and the root of the runtime image an app's images copy from). It unifies into the app's own package, so it carries that package's
// name, read from the program it sits beside.
async function mode(appDir: string, local: boolean): Promise<void> {
  const cwd = `${pathToFileURL(Deno.cwd()).href}/`;
  const dir = new URL(`${appDir.replace(/\/*$/, "")}/`, cwd);
  const program = await Deno.readTextFile(new URL("program.cue", dir));
  const declared = program.match(/^package\s+(\w+)\s*$/m);
  if (declared === null) throw new Error(`${appDir}/program.cue declares no package`);
  const runtime = local ? pathFrom(dirPath(dir), dirPath(new URL("./", import.meta.url))) : "";
  const source = local ? `${pathFrom(dirPath(dir), dirPath(root))}/` : "";
  console.log(
    [
      "// generated by omnishell from the layout this app is built in — do not edit",
      "",
      `package ${declared[1]}`,
      "",
      `terminal: surface: {`,
      `  runtime: ${JSON.stringify(runtime)}`,
      `  interpreterRoot: ${JSON.stringify(`${source}interpreter`)}`,
      `  componentsRoot: ${JSON.stringify(`${source}components`)}`,
      `  markupReader: ${JSON.stringify(`${source}read-markup.ts`)}`,
      `  machineSchema: ${JSON.stringify(`${source}machine.cue`)}`,
      `}`,
    ].join("\n"),
  );
}

const [verb, ...rest] = Deno.args;

if (verb === "mode") {
  const [appDir, ...flags] = rest;
  if (appDir === undefined) refuse("mode: no app directory");
  if (flags.length > 1 || (flags.length === 1 && flags[0] !== "--local")) {
    refuse(`mode: ${flags.join(" ")}`);
  }
  await narrow(false);
  await mode(appDir, flags[0] === "--local");
} else if (verb === "check" || verb === "read") {
  const [noun, ...args] = rest;
  if (noun === undefined) refuse(`${verb}: no leaf`);
  const leaf = `${verb} ${noun}`;
  if (args.length !== 1) refuse(`${leaf}: one <appDir> or --self-test`);
  switch (leaf) {
    case "check markup": {
      const { run } = await import("../check-markup.ts");
      await narrow(false);
      await run(args);
      break;
    }
    case "check handlers": {
      const { run } = await import("../check-handlers.ts");
      await narrow(true);
      await run(args);
      break;
    }
    case "check battery": {
      const { run } = await import("../check-battery.ts");
      await narrow(true);
      await run(args);
      break;
    }
    case "check machines": {
      const { run } = await import("../check-machines.ts");
      await narrow(true);
      await run(args);
      break;
    }
    case "check parity": {
      const { run } = await import("../check-parity.ts");
      await narrow(true);
      await run(args);
      break;
    }
    case "check i18n": {
      const { run } = await import("../check-i18n.ts");
      await narrow(true);
      await run(args);
      break;
    }
    case "read markup": {
      const { run } = await import("../read-markup.ts");
      await narrow(false);
      await run(args);
      break;
    }
    default:
      refuse(`no such check: ${leaf}`);
  }
} else {
  refuse(verb === undefined ? "omnishell: no subcommand" : `no such subcommand: ${verb}`);
}
