// generated by pronto from the layout this app is built in — do not edit

package truco

loop: surface: sources: pronto: "../../plugins/pronto"
build: meta: dir: "apps/truco"
cluster: meta: root: "../../"
cluster: meta: runtime: "../../"
