// generated by omnishell from the layout this app is built in — do not edit

package truco

terminal: surface: {
  runtime: "../../plugins/omnishell/runtime"
  interpreterRoot: "../../plugins/omnishell/interpreter"
  componentsRoot: "../../plugins/omnishell/components"
  markupReader: "../../plugins/omnishell/read-markup.ts"
  machineSchema: "../../plugins/omnishell/machine.cue"
}
