-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

-- portable type domains for PostgreSQL 18 and PostgREST 12.2.3
--
-- This migration is deliberately one-shot. Domains cannot be altered safely
-- into a different type contract, so a changed type is a new migration.
SET search_path = public, pg_catalog;

CREATE OR REPLACE FUNCTION public.portable_json_scalar_text(value json, expected text)
RETURNS text
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
BEGIN
  IF json_typeof(value) <> expected THEN
    RAISE EXCEPTION 'expected JSON %, got %', expected, json_typeof(value) USING ERRCODE = '22023';
  END IF;
  RETURN value #>> '{}';
END;
$$;

CREATE OR REPLACE FUNCTION public.portable_canonical_integer(value text, lo bigint, hi bigint)
RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value ~ '^(0|-?[1-9][0-9]*)$' AND value::numeric >= lo AND value::numeric <= hi;

CREATE OR REPLACE FUNCTION public.portable_reject(message text)
RETURNS text
LANGUAGE plpgsql VOLATILE PARALLEL SAFE
AS $$
BEGIN
  RAISE EXCEPTION '%', message USING ERRCODE = '22023';
END;
$$;

CREATE OR REPLACE FUNCTION public.portable_finite_double(value double precision)
RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value <> 'Infinity'::double precision
  AND value <> '-Infinity'::double precision
  AND value <> 'NaN'::double precision;

CREATE OR REPLACE FUNCTION public.portable_base64(value text)
RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value ~ '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$';

CREATE OR REPLACE FUNCTION public.portable_timezone(value text)
RETURNS boolean
LANGUAGE sql STABLE STRICT PARALLEL SAFE
RETURN (value = 'UTC' OR value LIKE '%/%')
  AND EXISTS (SELECT 1 FROM pg_timezone_names WHERE name = value);

CREATE OR REPLACE FUNCTION public.portable_duration_valid(value interval)
RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN extract(month FROM value) = 0
  AND extract(year FROM value) = 0
  AND extract(day FROM value) = 0
  AND value >= interval '0 seconds'
  AND extract(epoch FROM value) <= 315576000000::numeric;

CREATE OR REPLACE FUNCTION public.portable_decimal_valid(value numeric, digits integer, fraction_digits integer)
RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value = trunc(value, fraction_digits)
  AND abs(value) < power(10::numeric, digits - fraction_digits);

CREATE OR REPLACE FUNCTION public.portable_json_number_valid(value json)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE binary64 double precision;
DECLARE source numeric;
BEGIN
  IF json_typeof(value) <> 'number' THEN RETURN false; END IF;
  BEGIN
    source := (value #>> '{}')::numeric;
    binary64 := source::double precision;
  EXCEPTION WHEN numeric_value_out_of_range OR invalid_text_representation THEN
    RETURN false;
  END;
  RETURN portable_finite_double(binary64) AND source = binary64::text::numeric;
END;
$$;

CREATE OR REPLACE FUNCTION public.portable_json_valid(value json)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE item json;
BEGIN
  CASE json_typeof(value)
    WHEN 'number' THEN RETURN portable_json_number_valid(value);
    WHEN 'array' THEN
      FOR item IN SELECT json_array_elements(value) LOOP
        IF portable_json_valid(item) IS NOT TRUE THEN RETURN false; END IF;
      END LOOP;
    WHEN 'object' THEN
      IF EXISTS (SELECT entry.key FROM json_each($1) AS entry GROUP BY entry.key HAVING count(*) > 1) THEN RETURN false; END IF;
      FOR item IN SELECT entry.value FROM json_each($1) AS entry LOOP
        IF portable_json_valid(item) IS NOT TRUE THEN RETURN false; END IF;
      END LOOP;
    WHEN 'string' THEN
      BEGIN
        PERFORM value #>> '{}';
      EXCEPTION WHEN character_not_in_repertoire OR invalid_text_representation THEN
        RETURN false;
      END;
      RETURN true;
    WHEN 'boolean', 'null' THEN RETURN true;
    ELSE RETURN false;
  END CASE;
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.portable_geojson_position_valid(value json)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE longitude double precision;
DECLARE latitude double precision;
BEGIN
  IF json_typeof(value) IS DISTINCT FROM 'array' OR json_array_length(value) NOT IN (2, 3) THEN RETURN false; END IF;
  IF portable_json_number_valid(value -> 0) IS NOT TRUE OR portable_json_number_valid(value -> 1) IS NOT TRUE THEN RETURN false; END IF;
  IF json_array_length(value) = 3 AND portable_json_number_valid(value -> 2) IS NOT TRUE THEN RETURN false; END IF;
  longitude := (value ->> 0)::double precision;
  latitude := (value ->> 1)::double precision;
  RETURN longitude BETWEEN -180 AND 180 AND latitude BETWEEN -90 AND 90;
END;
$$;

CREATE OR REPLACE FUNCTION public.portable_geojson_positions_valid(value json, minimum integer)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE item json;
BEGIN
  IF json_typeof(value) IS DISTINCT FROM 'array' OR json_array_length(value) < minimum THEN RETURN false; END IF;
  FOR item IN SELECT json_array_elements(value) LOOP
    IF portable_geojson_position_valid(item) IS NOT TRUE THEN RETURN false; END IF;
  END LOOP;
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.portable_geojson_ring_valid(value json)
RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN COALESCE(portable_geojson_positions_valid(value, 4)
  AND ((value -> 0 ->> 0)::numeric = (value -> (json_array_length(value) - 1) ->> 0)::numeric)
  AND ((value -> 0 ->> 1)::numeric = (value -> (json_array_length(value) - 1) ->> 1)::numeric), false);

CREATE OR REPLACE FUNCTION public.portable_geojson_geometry_valid(value json)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE kind text;
DECLARE coordinates json;
DECLARE item json;
BEGIN
  IF json_typeof(value) IS DISTINCT FROM 'object' OR json_object_field(value, 'crs') IS NOT NULL THEN RETURN false; END IF;
  kind := value ->> 'type';
  CASE kind
    WHEN 'Point' THEN RETURN portable_geojson_position_valid(value -> 'coordinates');
    WHEN 'MultiPoint' THEN RETURN portable_geojson_positions_valid(value -> 'coordinates', 0);
    WHEN 'LineString' THEN RETURN portable_geojson_positions_valid(value -> 'coordinates', 2);
    WHEN 'MultiLineString' THEN
      coordinates := value -> 'coordinates';
      IF json_typeof(coordinates) IS DISTINCT FROM 'array' THEN RETURN false; END IF;
      FOR item IN SELECT json_array_elements(coordinates) LOOP
        IF portable_geojson_positions_valid(item, 2) IS NOT TRUE THEN RETURN false; END IF;
      END LOOP;
      RETURN true;
    WHEN 'Polygon' THEN
      coordinates := value -> 'coordinates';
      IF json_typeof(coordinates) IS DISTINCT FROM 'array' OR json_array_length(coordinates) = 0 THEN RETURN false; END IF;
      FOR item IN SELECT json_array_elements(coordinates) LOOP
        IF portable_geojson_ring_valid(item) IS NOT TRUE THEN RETURN false; END IF;
      END LOOP;
      RETURN true;
    WHEN 'MultiPolygon' THEN
      coordinates := value -> 'coordinates';
      IF json_typeof(coordinates) IS DISTINCT FROM 'array' THEN RETURN false; END IF;
      FOR item IN SELECT json_array_elements(coordinates) LOOP
        IF json_typeof(item) IS DISTINCT FROM 'array' OR json_array_length(item) = 0 THEN RETURN false; END IF;
        IF EXISTS (SELECT 1 FROM json_array_elements(item) AS ring WHERE portable_geojson_ring_valid(ring) IS NOT TRUE) THEN RETURN false; END IF;
      END LOOP;
      RETURN true;
    WHEN 'GeometryCollection' THEN
      coordinates := value -> 'geometries';
      IF json_typeof(coordinates) IS DISTINCT FROM 'array' THEN RETURN false; END IF;
      FOR item IN SELECT json_array_elements(coordinates) LOOP
        IF portable_geojson_geometry_valid(item) IS NOT TRUE THEN RETURN false; END IF;
      END LOOP;
      RETURN true;
    ELSE RETURN false;
  END CASE;
END;
$$;

CREATE OR REPLACE FUNCTION public.portable_geojson_valid(value json)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE item json;
DECLARE properties json;
BEGIN
  IF json_typeof(value) IS DISTINCT FROM 'object' THEN RETURN false; END IF;
  CASE value ->> 'type'
    WHEN 'Feature' THEN
      properties := value -> 'properties';
      RETURN json_object_field(value, 'geometry') IS NOT NULL
        AND json_object_field(value, 'properties') IS NOT NULL
        AND json_typeof(properties) IN ('object', 'null')
        AND (json_typeof(value -> 'geometry') = 'null' OR portable_geojson_geometry_valid(value -> 'geometry') IS TRUE);
    WHEN 'FeatureCollection' THEN
      IF json_object_field(value, 'features') IS NULL OR json_typeof(value -> 'features') IS DISTINCT FROM 'array' THEN RETURN false; END IF;
      FOR item IN SELECT json_array_elements(value -> 'features') LOOP
        IF portable_geojson_valid(item) IS NOT TRUE OR item ->> 'type' IS DISTINCT FROM 'Feature' THEN RETURN false; END IF;
      END LOOP;
      RETURN true;
    ELSE RETURN portable_geojson_geometry_valid(value);
  END CASE;
END;
$$;

CREATE DOMAIN public.portable_string AS text CHECK (VALUE IS NULL OR COALESCE((true), false));
CREATE DOMAIN public.portable_bool AS boolean CHECK (VALUE IS NULL OR COALESCE((true), false));
CREATE DOMAIN public.portable_int32 AS integer CHECK (VALUE IS NULL OR COALESCE((true), false));
CREATE DOMAIN public.portable_int64 AS bigint CHECK (VALUE IS NULL OR COALESCE((true), false));
CREATE DOMAIN public.portable_double AS double precision CHECK (VALUE IS NULL OR COALESCE((portable_finite_double(VALUE)), false));
CREATE DOMAIN public.portable_bytes AS bytea CHECK (VALUE IS NULL OR COALESCE((true), false));
CREATE DOMAIN public.portable_uuid AS uuid CHECK (VALUE IS NULL OR COALESCE((true), false));
CREATE DOMAIN public.portable_timestamp AS timestamptz CHECK (VALUE IS NULL OR COALESCE((VALUE >= timestamptz '0001-01-01 00:00:00+00' AND VALUE < timestamptz '10000-01-01 00:00:00+00'), false));
CREATE DOMAIN public.portable_date AS date CHECK (VALUE IS NULL OR COALESCE((VALUE >= date '0001-01-01' AND VALUE < date '10000-01-01'), false));
CREATE DOMAIN public.portable_time AS time(6) CHECK (VALUE IS NULL OR COALESCE((VALUE < time '24:00:00'), false));
CREATE DOMAIN public.portable_timezone AS text CHECK (VALUE IS NULL OR COALESCE((portable_timezone(VALUE)), false));
CREATE DOMAIN public.portable_duration AS interval CHECK (VALUE IS NULL OR COALESCE((portable_duration_valid(VALUE)), false));
CREATE DOMAIN public.portable_json AS json CHECK (VALUE IS NULL OR COALESCE((portable_json_valid(VALUE)), false));
CREATE DOMAIN public.portable_geojson AS json CHECK (VALUE IS NULL OR COALESCE((portable_json_valid(VALUE) AND portable_geojson_valid(VALUE)), false));


CREATE OR REPLACE FUNCTION public.portable_string_from_json(value json)
RETURNS public.portable_string
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN portable_json_scalar_text(value, 'string')::public.portable_string;

CREATE OR REPLACE FUNCTION public.portable_string_from_text(value text)
RETURNS public.portable_string
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::public.portable_string;

CREATE OR REPLACE FUNCTION public.portable_string_to_json(value public.portable_string)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(value::text);

CREATE CAST (json AS public.portable_string) WITH FUNCTION public.portable_string_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_string) WITH FUNCTION public.portable_string_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_string AS json) WITH FUNCTION public.portable_string_to_json(public.portable_string) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_bool_from_json(value json)
RETURNS public.portable_bool
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN portable_json_scalar_text(value, 'boolean')::boolean::public.portable_bool;

CREATE OR REPLACE FUNCTION public.portable_bool_from_text(value text)
RETURNS public.portable_bool
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE value WHEN 'true' THEN true WHEN 'false' THEN false ELSE portable_reject('portable_bool must be true or false')::boolean END::public.portable_bool;

CREATE OR REPLACE FUNCTION public.portable_bool_to_json(value public.portable_bool)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(value::boolean);

CREATE CAST (json AS public.portable_bool) WITH FUNCTION public.portable_bool_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_bool) WITH FUNCTION public.portable_bool_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_bool AS json) WITH FUNCTION public.portable_bool_to_json(public.portable_bool) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_int32_from_json(value json)
RETURNS public.portable_int32
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_canonical_integer(portable_json_scalar_text(value, 'number'), -2147483648, 2147483647) THEN portable_json_scalar_text(value, 'number')::integer ELSE portable_reject('portable_int32 must be a canonical JSON integer')::integer END::public.portable_int32;

CREATE OR REPLACE FUNCTION public.portable_int32_from_text(value text)
RETURNS public.portable_int32
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_canonical_integer(value, -2147483648, 2147483647) THEN value::integer ELSE portable_reject('portable_int32 must be canonical')::integer END::public.portable_int32;

CREATE OR REPLACE FUNCTION public.portable_int32_to_json(value public.portable_int32)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(value::integer);

CREATE CAST (json AS public.portable_int32) WITH FUNCTION public.portable_int32_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_int32) WITH FUNCTION public.portable_int32_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_int32 AS json) WITH FUNCTION public.portable_int32_to_json(public.portable_int32) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_int64_from_json(value json)
RETURNS public.portable_int64
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_canonical_integer(portable_json_scalar_text(value, 'string'), -9223372036854775808, 9223372036854775807) THEN portable_json_scalar_text(value, 'string')::bigint ELSE portable_reject('portable_int64 must be a canonical JSON string')::bigint END::public.portable_int64;

CREATE OR REPLACE FUNCTION public.portable_int64_from_text(value text)
RETURNS public.portable_int64
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_canonical_integer(value, -9223372036854775808, 9223372036854775807) THEN value::bigint ELSE portable_reject('portable_int64 must be canonical')::bigint END::public.portable_int64;

CREATE OR REPLACE FUNCTION public.portable_int64_to_json(value public.portable_int64)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(value::text);

CREATE CAST (json AS public.portable_int64) WITH FUNCTION public.portable_int64_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_int64) WITH FUNCTION public.portable_int64_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_int64 AS json) WITH FUNCTION public.portable_int64_to_json(public.portable_int64) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_double_from_json(value json)
RETURNS public.portable_double
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN portable_json_scalar_text(value, 'number')::double precision::public.portable_double;

CREATE OR REPLACE FUNCTION public.portable_double_from_text(value text)
RETURNS public.portable_double
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::double precision::public.portable_double;

CREATE OR REPLACE FUNCTION public.portable_double_to_json(value public.portable_double)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(value::double precision);

CREATE CAST (json AS public.portable_double) WITH FUNCTION public.portable_double_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_double) WITH FUNCTION public.portable_double_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_double AS json) WITH FUNCTION public.portable_double_to_json(public.portable_double) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_bytes_from_json(value json)
RETURNS public.portable_bytes
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_base64(portable_json_scalar_text(value, 'string')) THEN decode(portable_json_scalar_text(value, 'string'), 'base64') ELSE portable_reject('portable_bytes must be strict base64')::bytea END::public.portable_bytes;

CREATE OR REPLACE FUNCTION public.portable_bytes_from_text(value text)
RETURNS public.portable_bytes
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_base64(value) THEN decode(value, 'base64') ELSE portable_reject('portable_bytes must be strict base64')::bytea END::public.portable_bytes;

CREATE OR REPLACE FUNCTION public.portable_bytes_to_json(value public.portable_bytes)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(replace(encode(value::bytea, 'base64'), E'\n', ''));

CREATE CAST (json AS public.portable_bytes) WITH FUNCTION public.portable_bytes_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_bytes) WITH FUNCTION public.portable_bytes_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_bytes AS json) WITH FUNCTION public.portable_bytes_to_json(public.portable_bytes) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_uuid_from_json(value json)
RETURNS public.portable_uuid
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_json_scalar_text(value, 'string') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN portable_json_scalar_text(value, 'string')::uuid ELSE portable_reject('portable_uuid must be lowercase and hyphenated')::uuid END::public.portable_uuid;

CREATE OR REPLACE FUNCTION public.portable_uuid_from_text(value text)
RETURNS public.portable_uuid
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN value ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN value::uuid ELSE portable_reject('portable_uuid must be lowercase and hyphenated')::uuid END::public.portable_uuid;

CREATE OR REPLACE FUNCTION public.portable_uuid_to_json(value public.portable_uuid)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(lower(value::uuid::text));

CREATE CAST (json AS public.portable_uuid) WITH FUNCTION public.portable_uuid_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_uuid) WITH FUNCTION public.portable_uuid_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_uuid AS json) WITH FUNCTION public.portable_uuid_to_json(public.portable_uuid) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_timestamp_from_json(value json)
RETURNS public.portable_timestamp
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_json_scalar_text(value, 'string') ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\.[0-9]{6}Z$' THEN portable_json_scalar_text(value, 'string')::timestamptz ELSE portable_reject('portable_timestamp must be UTC with exactly six fractional digits')::timestamptz END::public.portable_timestamp;

CREATE OR REPLACE FUNCTION public.portable_timestamp_from_text(value text)
RETURNS public.portable_timestamp
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN value ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\.[0-9]{6}Z$' THEN value::timestamptz ELSE portable_reject('portable_timestamp must be UTC with exactly six fractional digits')::timestamptz END::public.portable_timestamp;

CREATE OR REPLACE FUNCTION public.portable_timestamp_to_json(value public.portable_timestamp)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(to_char(value::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'));

CREATE CAST (json AS public.portable_timestamp) WITH FUNCTION public.portable_timestamp_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_timestamp) WITH FUNCTION public.portable_timestamp_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_timestamp AS json) WITH FUNCTION public.portable_timestamp_to_json(public.portable_timestamp) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_date_from_json(value json)
RETURNS public.portable_date
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_json_scalar_text(value, 'string') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN portable_json_scalar_text(value, 'string')::date ELSE portable_reject('portable_date must be RFC 3339 full-date')::date END::public.portable_date;

CREATE OR REPLACE FUNCTION public.portable_date_from_text(value text)
RETURNS public.portable_date
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN value ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN value::date ELSE portable_reject('portable_date must be RFC 3339 full-date')::date END::public.portable_date;

CREATE OR REPLACE FUNCTION public.portable_date_to_json(value public.portable_date)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(to_char(value::date, 'YYYY-MM-DD'));

CREATE CAST (json AS public.portable_date) WITH FUNCTION public.portable_date_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_date) WITH FUNCTION public.portable_date_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_date AS json) WITH FUNCTION public.portable_date_to_json(public.portable_date) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_time_from_json(value json)
RETURNS public.portable_time
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_json_scalar_text(value, 'string') ~ '^[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}$' AND portable_json_scalar_text(value, 'string') < '24:00:00.000000' THEN portable_json_scalar_text(value, 'string')::time ELSE portable_reject('portable_time must be HH:mm:ss.ffffff before 24:00')::time END::public.portable_time;

CREATE OR REPLACE FUNCTION public.portable_time_from_text(value text)
RETURNS public.portable_time
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN value ~ '^[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}$' AND value < '24:00:00.000000' THEN value::time ELSE portable_reject('portable_time must be HH:mm:ss.ffffff before 24:00')::time END::public.portable_time;

CREATE OR REPLACE FUNCTION public.portable_time_to_json(value public.portable_time)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(to_char(value::time, 'HH24:MI:SS.US'));

CREATE CAST (json AS public.portable_time) WITH FUNCTION public.portable_time_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_time) WITH FUNCTION public.portable_time_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_time AS json) WITH FUNCTION public.portable_time_to_json(public.portable_time) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_timezone_from_json(value json)
RETURNS public.portable_timezone
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN portable_json_scalar_text(value, 'string')::public.portable_timezone;

CREATE OR REPLACE FUNCTION public.portable_timezone_from_text(value text)
RETURNS public.portable_timezone
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::public.portable_timezone;

CREATE OR REPLACE FUNCTION public.portable_timezone_to_json(value public.portable_timezone)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json(value::text);

CREATE CAST (json AS public.portable_timezone) WITH FUNCTION public.portable_timezone_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_timezone) WITH FUNCTION public.portable_timezone_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_timezone AS json) WITH FUNCTION public.portable_timezone_to_json(public.portable_timezone) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_duration_from_json(value json)
RETURNS public.portable_duration
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN portable_json_scalar_text(value, 'string') ~ '^PT(0|[1-9][0-9]*)(\.[0-9]{0,5}[1-9])?S$' THEN (substring(portable_json_scalar_text(value, 'string') FROM 3 FOR char_length(portable_json_scalar_text(value, 'string')) - 3) || ' seconds')::interval ELSE portable_reject('portable_duration must be canonical total seconds at microsecond precision')::interval END::public.portable_duration;

CREATE OR REPLACE FUNCTION public.portable_duration_from_text(value text)
RETURNS public.portable_duration
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN CASE WHEN value ~ '^PT(0|[1-9][0-9]*)(\.[0-9]{0,5}[1-9])?S$' THEN (substring(value FROM 3 FOR char_length(value) - 3) || ' seconds')::interval ELSE portable_reject('portable_duration must be canonical total seconds at microsecond precision')::interval END::public.portable_duration;

CREATE OR REPLACE FUNCTION public.portable_duration_to_json(value public.portable_duration)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN to_json('PT' || trim_scale(extract(epoch FROM value::interval))::text || 'S');

CREATE CAST (json AS public.portable_duration) WITH FUNCTION public.portable_duration_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_duration) WITH FUNCTION public.portable_duration_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_duration AS json) WITH FUNCTION public.portable_duration_to_json(public.portable_duration) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_json_from_json(value json)
RETURNS public.portable_json
LANGUAGE sql IMMUTABLE CALLED ON NULL INPUT PARALLEL SAFE
RETURN COALESCE(value, 'null'::json)::public.portable_json;

CREATE OR REPLACE FUNCTION public.portable_json_from_text(value text)
RETURNS public.portable_json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::json::public.portable_json;

CREATE OR REPLACE FUNCTION public.portable_json_to_json(value public.portable_json)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::json;

CREATE CAST (json AS public.portable_json) WITH FUNCTION public.portable_json_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_json) WITH FUNCTION public.portable_json_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_json AS json) WITH FUNCTION public.portable_json_to_json(public.portable_json) AS IMPLICIT;

CREATE OR REPLACE FUNCTION public.portable_geojson_from_json(value json)
RETURNS public.portable_geojson
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::public.portable_geojson;

CREATE OR REPLACE FUNCTION public.portable_geojson_from_text(value text)
RETURNS public.portable_geojson
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::json::public.portable_geojson;

CREATE OR REPLACE FUNCTION public.portable_geojson_to_json(value public.portable_geojson)
RETURNS json
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::json;

CREATE CAST (json AS public.portable_geojson) WITH FUNCTION public.portable_geojson_from_json(json) AS IMPLICIT;
CREATE CAST (text AS public.portable_geojson) WITH FUNCTION public.portable_geojson_from_text(text) AS IMPLICIT;
CREATE CAST (public.portable_geojson AS json) WITH FUNCTION public.portable_geojson_to_json(public.portable_geojson) AS IMPLICIT;


COMMIT;
