-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CREATE OR REPLACE FUNCTION restamp_txid() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.txid := pg_current_xact_id()::text::bigint;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS restamp_txid ON app_user;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON app_user
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON lobby;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON lobby
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON challenge;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON challenge
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON room_action;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON room_action
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();

COMMIT;
