-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

-- No server-durability entity: nothing for the bus to read.

-- Electric's own publication, declared rather than left to it.
-- ELECTRIC_MANUAL_TABLE_PUBLISHING makes it validate this instead of
-- building one, which is what lets its role hold only REPLICATION and
-- SELECT: creating a publication needs CREATE on the database, and
-- adding a table to one needs ownership of that table. A sync service
-- that owns the app's tables can drop them.
-- tier: container
DO $$ DECLARE t text; BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'electric_publication_default') THEN
    CREATE PUBLICATION electric_publication_default FOR TABLE app_user,lobby,challenge,room_action WITH (publish_generated_columns = stored);
  END IF;
  FOREACH t IN ARRAY ARRAY['app_user','lobby','challenge','room_action'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                   WHERE pubname = 'electric_publication_default' AND schemaname = 'public' AND tablename = t) THEN
      EXECUTE format('ALTER PUBLICATION electric_publication_default ADD TABLE %I', t);
    END IF;
  END LOOP;
END $$;

ALTER TABLE app_user REPLICA IDENTITY FULL;
ALTER TABLE lobby REPLICA IDENTITY FULL;
ALTER TABLE challenge REPLICA IDENTITY FULL;
ALTER TABLE room_action REPLICA IDENTITY FULL;
-- tier: any
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon;

COMMIT;
