-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

ALTER TABLE "challenge" DROP CONSTRAINT IF EXISTS "challenge_status_check";
ALTER TABLE "challenge" ADD CONSTRAINT "challenge_status_check" CHECK ("status" IN ('pending', 'accepted', 'declined', 'expired')) NOT VALID;

CREATE OR REPLACE FUNCTION "trg_challenge_status_machine"() RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND OLD."status" = NEW."status" THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'pending' THEN
      RAISE EXCEPTION 'new % must start in initial state % (got %)', 'challenge', 'pending', NEW."status" USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF OLD."status" = 'pending' THEN
      -- Timeout check: state pending expires after 60000ms
      IF NEW."status" <> 'expired' AND OLD.created_at < (now() - interval '60000 milliseconds') THEN
        RAISE EXCEPTION '% in state % has expired (timeout after %ms)', 'challenge', 'pending', '60000' USING ERRCODE = 'check_violation';
      END IF;
      IF NEW."status" NOT IN ('accepted', 'declined', 'expired') THEN
        RAISE EXCEPTION 'invalid transition on % from % to %', 'challenge', OLD."status", NEW."status" USING ERRCODE = 'check_violation';
      END IF;

      IF NEW."status" = 'accepted' THEN

        RETURN NEW;
      END IF;
      IF NEW."status" = 'declined' THEN

        RETURN NEW;
      END IF;
      IF NEW."status" = 'expired' THEN

        RETURN NEW;
      END IF;
      RETURN NEW;
    END IF;
    IF OLD."status" = 'accepted' THEN
      RAISE EXCEPTION 'cannot transition from final state % on %', OLD."status", 'challenge' USING ERRCODE = 'check_violation';
    END IF;
    IF OLD."status" = 'declined' THEN
      RAISE EXCEPTION 'cannot transition from final state % on %', OLD."status", 'challenge' USING ERRCODE = 'check_violation';
    END IF;
    IF OLD."status" = 'expired' THEN
      RAISE EXCEPTION 'cannot transition from final state % on %', OLD."status", 'challenge' USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS "trg_challenge_status_machine" ON "challenge";
CREATE TRIGGER "trg_challenge_status_machine"
  BEFORE INSERT OR UPDATE ON "challenge"
  FOR EACH ROW
  EXECUTE FUNCTION "trg_challenge_status_machine"();

COMMIT;
