-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

GRANT USAGE ON SCHEMA public TO anon, app_user, service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user, service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user, service;

COMMIT;
