-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CREATE TABLE IF NOT EXISTS app_user (
  "id" uuid PRIMARY KEY,
  "handle" TEXT NOT NULL UNIQUE,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('user:' || "id") STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS lobby (
  "id" TEXT PRIMARY KEY CHECK (char_length(id) <= 64),
  "handle" TEXT NOT NULL CHECK (char_length(handle) > 0 AND char_length(handle) <= 40),
  "room_seed" TEXT NOT NULL CHECK (char_length(room_seed) <= 64),
  "status" TEXT NOT NULL CHECK (status IN ('waiting', 'playing')),
  "updated_at" TIMESTAMPTZ,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS challenge (
  "id" TEXT PRIMARY KEY CHECK (char_length(id) <= 64),
  "challenger_id" TEXT NOT NULL CHECK (char_length(challenger_id) <= 64),
  "challenger_name" TEXT NOT NULL CHECK (char_length(challenger_name) > 0 AND char_length(challenger_name) <= 40),
  "target_id" TEXT NOT NULL CHECK (char_length(target_id) <= 64),
  "seed" TEXT NOT NULL CHECK (char_length(seed) <= 64),
  "status" TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'declined', 'expired')),
  "created_at" TIMESTAMPTZ,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS room_action (
  "id" TEXT PRIMARY KEY CHECK (char_length(id) <= 64),
  "room_seed" TEXT NOT NULL CHECK (char_length(room_seed) <= 64),
  "player_id" TEXT NOT NULL CHECK (char_length(player_id) <= 64),
  "action" TEXT NOT NULL CHECK (action IN ('play_card', 'truco', 'accept', 'run', 'touch_card', 'resign')),
  "card" TEXT CHECK (char_length(card) <= 4),
  "slot" INTEGER CHECK (slot >= 0 AND slot <= 12),
  "created_at" TIMESTAMPTZ,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

COMMIT;
