-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

INSERT INTO mecha.rls_exempt VALUES ('public.app_user', 'internal except a person reading their own row, which the self-select policy alone allows') ON CONFLICT DO NOTHING;
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS app_user_self_select ON app_user;
CREATE POLICY app_user_self_select ON app_user FOR SELECT TO app_user USING (id = auth_uid());
DROP POLICY IF EXISTS app_user_service_all ON app_user;
CREATE POLICY app_user_service_all ON app_user FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('lobby');
ALTER TABLE lobby ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lobby_app_user_select ON lobby;
CREATE POLICY lobby_app_user_select ON lobby FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS lobby_service_all ON lobby;
CREATE POLICY lobby_service_all ON lobby FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('challenge');
ALTER TABLE challenge ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS challenge_app_user_select ON challenge;
CREATE POLICY challenge_app_user_select ON challenge FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS challenge_service_all ON challenge;
CREATE POLICY challenge_service_all ON challenge FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('room_action');
ALTER TABLE room_action ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS room_action_app_user_select ON room_action;
CREATE POLICY room_action_app_user_select ON room_action FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS room_action_service_all ON room_action;
CREATE POLICY room_action_service_all ON room_action FOR ALL TO service USING (true) WITH CHECK (true);

COMMIT;
